Repository ember-lifeline/ember-lifeline, pull requests merged in 2021-05, with the labels that each got.

#988 Adds deprecation warning for DOM APIs
  .github/workflows/ci-build.yml
  addon/dom-event-listeners.ts
  config/ember-try.js
  yarn.lock
Labels: documentation

#990 Cleanup, deprecation removal, and blueprint updating.
  .editorconfig
  .eslintrc.js
  .github/workflows/ci-build.yml
  .gitignore
  README.md
  addon/dom-event-listeners.ts
  addon/index.ts
  addon/mixins/disposable.ts
  addon/mixins/dom.ts
  addon/mixins/run.ts
  addon/run-task.ts
  addon/utils/disposable.ts
  config/ember-try.js
  hound.yml
  package.json
  testem.js
  tests/acceptance/cleanup-test.js
  tests/dummy/app/app.js
  tests/dummy/app/components/run-task-demo.js
  tests/dummy/app/routes/foo.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/components/run-task-demo.hbs
  tests/dummy/app/templates/docs.hbs
  tests/dummy/app/templates/index.hbs
  tests/dummy/app/templates/not-found.hbs
  tests/dummy/config/optional-features.json
  tests/dummy/config/targets.js
  tests/index.html
  tests/test-helper.js
  tests/unit/debounce-task-test.js
  tests/unit/dom-event-listeners-test.js
  tests/unit/mixins/dom-test.js
  tests/unit/mixins/run-test.js
  tests/unit/poll-task-test.js
  tests/unit/run-task-test.js
  tests/unit/setup-lifeline-validation-test.js
  tests/unit/utils/disposable-test.js
  yarn.lock
Labels: breaking, dependencies

#1003 Add Embroider CI scenarios
  config/ember-try.js
  ember-cli-build.js
  package.json
  yarn.lock
Labels: internal
